### ISSUE TITLE
Opensource? 

### ISSUE THREAD

**Issue by Xiaoyang-Rebecca** [mlomnitz/DiffJPEG#3]
Hi @mlomnitz 

I was wondering if your repository could be open sourced.

If so, please add the MIT license to the root folder.

Feel free to ask me question.

**Comment by mlomnitz** [comment]
Hello Xiaoyang-Rebecca, 

  I have added the MIT license.  Please let me know if there is anything else I can do to help or add to the functionality.

Michael

**Comment by Xiaoyang-Rebecca** [comment]
Good thanks!
